# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 06:15
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', bitfield.models.BitField(('awesome_flag', 'flaggy_foo', 'baz_bar'), default=None)),
            ],
        ),
    ]
