# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_application', to='demo.Application')),
                ('to_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_application', to='demo.Application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='depends_on',
            field=models.ManyToManyField(related_name='used_by', through='demo.ApplicationDependency', to='demo.Application'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdependency',
            unique_together=set([('from_application', 'to_application')]),
        ),
    ]
